"""End-to-end integration tests for the auto-update PowerShell script.

These tests drive the ACTUAL PS1 generated by ``_build_ps_script``
through a real ``powershell.exe`` process against fake on-disk files.
They're the regression lock-in for the series of "clicked Yes, nothing
happened" bug reports — previously only unit-tests on Python side
existed and the PS1 itself was never exercised.

Each test covers one of the four code paths:

    * happy         — new.exe is valid, Move succeeds, no status file.
    * TRUNCATED     — new.exe is < 1 MB → preflight fails → status file.
    * VANISHED      — new.exe doesn't exist → preflight fails → status file.
    * ROLLED_BACK   — Move-Item fails → rollback → status file with reason.

Windows-only: PowerShell, Rename-Item, Move-Item are all Win32-specific.
Skipped cleanly elsewhere.

Launch step is suppressed via ``launch_process=False`` — the fake files
aren't valid PE binaries, so Start-Process would fail and derail the
real thing we want to test (Move atomicity + status reporting).
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

import pytest

from kn_gui.updater import _build_ps_script


requires_windows = pytest.mark.skipif(
    sys.platform != 'win32',
    reason='PS1 integration test requires powershell.exe (Windows only)',
)


def _run_ps(script_path: Path, timeout: float = 60) -> int:
    """Run the generated PS1 through a real powershell.exe. Returns
    the exit code. Stdio is DEVNULL'd just like in apply_update()."""
    proc = subprocess.run(
        [
            'powershell.exe',
            '-ExecutionPolicy', 'Bypass',
            '-NoProfile',
            '-NonInteractive',
            '-WindowStyle', 'Hidden',
            '-File', str(script_path),
        ],
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        timeout=timeout,
    )
    return proc.returncode


def _prepare(tmp_path: Path, *, new_size: int = 2_000_000,
              create_new: bool = True) -> dict:
    """Lay out a fake install directory and return paths + script."""
    cur = tmp_path / 'app.exe'
    new = tmp_path / 'app_new.exe'
    log = tmp_path / 'kfm_update.log'
    status = tmp_path / 'kfm_update_status.txt'

    # "Current" exe contains OLD_VERSION_BYTES + padding.
    cur.write_bytes(b'OLD_VERSION_BYTES' + b'\x00' * (2_000_000))
    if create_new:
        # "New" exe: marker + padding to the caller-specified size.
        marker = b'NEW_VERSION_BYTES'
        new.write_bytes(marker + b'\x00' * max(0, new_size - len(marker)))

    ps = _build_ps_script(
        current_exe=str(cur),
        new_exe_path=str(new),
        log_path=str(log),
        status_path=str(status),
        # Keep the integration test snappy: 2 retries × 0.5 s max.
        retries=3,
        initial_wait=1,
        retry_wait=1,
        launch_process=False,
    )
    ps_path = tmp_path / 'upd.ps1'
    ps_path.write_text(ps, encoding='utf-8-sig')

    return {'cur': cur, 'new': new, 'log': log,
            'status': status, 'ps_path': ps_path}


# ── Happy path ────────────────────────────────────────────────────────────

@requires_windows
def test_apply_update_happy_path(tmp_path):
    """new.exe is a valid >= 1 MB file → Move succeeds → cur.exe now
    contains the new content → status file is NOT written → log ends
    with SUCCESS."""
    env = _prepare(tmp_path, new_size=2_000_000)
    rc = _run_ps(env['ps_path'])

    assert rc == 0, f'powershell exited {rc}'
    assert env['cur'].exists(), 'cur.exe was removed'

    cur_bytes = env['cur'].read_bytes()
    assert cur_bytes.startswith(b'NEW_VERSION_BYTES'), (
        'cur.exe was not replaced with new.exe content')

    # The original "new" tempfile was moved, so it no longer exists.
    assert not env['new'].exists(), (
        f'new.exe still present — Move-Item did not complete')

    # Happy path: NO status file should be written.
    assert not env['status'].exists(), (
        f'status file unexpectedly written: {env["status"].read_text(encoding="utf-8")}')

    # Log must record SUCCESS.
    assert env['log'].exists()
    log_text = env['log'].read_text(encoding='utf-8')
    assert 'SUCCESS' in log_text, f'SUCCESS missing from log:\n{log_text}'


# ── TRUNCATED path (download was cut short / AV stub) ──────────────────────

@requires_windows
def test_apply_update_truncated_new_exe_writes_status(tmp_path):
    """new.exe < 1 MB → preflight refuses → status=TRUNCATED."""
    env = _prepare(tmp_path, new_size=500)  # way under 1 MB
    _run_ps(env['ps_path'])

    # cur.exe was NOT touched — rename never happened.
    assert env['cur'].exists()
    assert env['cur'].read_bytes().startswith(b'OLD_VERSION_BYTES')

    # Status file must report TRUNCATED.
    assert env['status'].exists(), (
        'status file missing — the whole point of this flow is to leave evidence')
    status = env['status'].read_text(encoding='utf-8-sig')
    assert status.startswith('TRUNCATED'), f'unexpected status kind:\n{status}'
    assert '500' in status  # the size should be mentioned


# ── VANISHED path (AV removed the new.exe between download and PS1) ────────

@requires_windows
def test_apply_update_vanished_new_exe_writes_status(tmp_path):
    """new.exe doesn't exist when PS1 runs → preflight refuses → VANISHED."""
    env = _prepare(tmp_path, create_new=False)
    _run_ps(env['ps_path'])

    # cur.exe untouched.
    assert env['cur'].exists()
    assert env['cur'].read_bytes().startswith(b'OLD_VERSION_BYTES')

    # Status must be VANISHED.
    assert env['status'].exists()
    status = env['status'].read_text(encoding='utf-8-sig')
    assert status.startswith('VANISHED'), f'unexpected status kind:\n{status}'


# ── ROLLED_BACK path (Move-Item fails) ────────────────────────────────────

@requires_windows
def test_apply_update_rollback_writes_status(tmp_path):
    """If Move-Item fails (we simulate by holding an exclusive OS lock on
    new.exe), the PS1 must exhaust retries, write ROLLED_BACK, and leave
    cur.exe in its original state."""
    env = _prepare(tmp_path, new_size=2_000_000)

    # Hold an exclusive lock on new.exe for the duration of the PS1 run.
    # On Windows, opening a file with Python's default open() + no share
    # grants GENERIC_READ/GENERIC_WRITE without FILE_SHARE_* — any
    # concurrent Move-Item from another process gets ERROR_SHARING_VIOLATION.
    handle = open(env['new'], 'rb+')
    try:
        rc = _run_ps(env['ps_path'], timeout=30)
    finally:
        handle.close()

    # cur.exe must have been restored to the original bytes. The rollback
    # branch in PS1 re-renames .bak back to .exe.
    assert env['cur'].exists()
    assert env['cur'].read_bytes().startswith(b'OLD_VERSION_BYTES'), (
        'cur.exe content changed — rollback did not restore the original')

    # .bak should not linger (rollback renames it back into place).
    assert not (tmp_path / 'app.exe.bak').exists(), (
        '.bak file left on disk — rollback missed it')

    # Status must record ROLLED_BACK with a reason.
    assert env['status'].exists()
    status = env['status'].read_text(encoding='utf-8-sig')
    assert status.startswith('ROLLED_BACK'), f'unexpected status kind:\n{status}'
    # Reason line should mention the type of Windows error.
    reason_line = status.splitlines()[1] if len(status.splitlines()) > 1 else ''
    assert reason_line, 'reason line is empty'


# ── Log breadcrumb always written ─────────────────────────────────────────

@requires_windows
def test_apply_update_always_writes_log(tmp_path):
    """Regardless of outcome, the log file must be populated — users
    will be directed to it from the status-file messagebox."""
    env = _prepare(tmp_path, create_new=False)  # VANISHED path
    _run_ps(env['ps_path'])
    assert env['log'].exists()
    text = env['log'].read_text(encoding='utf-8')
    assert 'apply_update started' in text
    assert 'script done' in text


# ── Script cleans up after itself ─────────────────────────────────────────

@requires_windows
def test_apply_update_removes_its_own_ps1(tmp_path):
    """The final line of the PS1 is Remove-Item $PSCommandPath — the
    script deletes its own file so %TEMP% doesn't accumulate cruft
    over time."""
    env = _prepare(tmp_path, new_size=2_000_000)
    _run_ps(env['ps_path'])
    assert not env['ps_path'].exists(), (
        'PS1 did not delete itself — %TEMP% would accumulate kfm_upd_*.ps1 '
        'files over repeated updates')
